devops/debug/main.go
=> feat(devops): adjust debug comment

quickstart/eino_assistant/eino/knowledge_indexing.json
=> feat(devops): delete httpclient of ark in knowledge_indexing json file

quickstart/chat/generate.go, quickstart/chat/main.go, quickstart/chat/ollama.go, quickstart/chat/openai.go, quickstart/chat/stream.go, quickstart/chat/template.go
=> feat: update quickstart_chat

compose/graph/simple/graph.go, compose/graph/simple/type_match_test.go, flow/agent/react/react.go, go.mod
=> fix: add some examples

quickstart/eino_assistant/cmd/einoagent/agent/agent.go
=> fix: add langfuse package

components/lambda/lambda.go
=> feat: add lambda example

.github/workflows/pr-check.yml, .github/workflows/tests.yml, .golangci.yaml, components/lambda/lambda.go, quickstart/eino_assistant/README.md, quickstart/eino_assistant/cmd/einoagent/main.go, quickstart/eino_assistant/cmd/einoagentcli/main.go, quickstart/eino_assistant/cmd/knowledgeindexing/main.go, quickstart/eino_assistant/go.mod, quickstart/eino_assistant/go.sum, quickstart/eino_assistant/pkg/env/env.go
feat: A new feature
为 eino assistant 示例增加 .env 文件的 auto load，减少用户启动成本
=> feat: add auto load env

go.mod, go.sum, quickstart/eino_assistant/go.mod, quickstart/eino_assistant/go.sum
=> feat(devops): upgrade devops

go.mod, go.sum, quickstart/eino_assistant/go.mod, quickstart/eino_assistant/go.sum
=> feat: upgrade eino to v0.3.14

devops/debug/graph/graph.go
=> feat: optimized devops debugging example

components/retriever/multiquery/main.go, compose/chain/main.go, compose/graph/tool_call_agent/tool_call_agent.go, compose/graph/tool_call_once/tool_call_once.go, compose/graph/two_model_chat/two_model_chat.go, flow/agent/multiagent/host/journal/host.go, flow/agent/multiagent/plan_execute/main.go, flow/agent/react/react.go, quickstart/chat/openai.go, quickstart/todoagent/main.go
=> feat: modify chat model env

flow/agent/react/react.go, go.mod, go.sum
feat: react example change to ark model, set StreamToolCallChecker
=> feat: react example change to ark model, set StreamToolCallChecker

compose/graph/two_model_chat/two_model_chat.go, go.mod, go.sum
=> feat: upgrade retriever/volc_vikingdb

flow/agent/multiagent/plan_execute/compose.go
=> feat: remove final length

flow/agent/react/react.go, go.mod, go.sum
=> feat: upgrade react agent version

compose/graph/tool_call_agent/tool_call_agent.go, flow/agent/multiagent/host/journal/main.go, flow/agent/react/react.go, quickstart/eino_assistant/pkg/tool/einotool/templates/http_agent/main.go
=> feat: replace deprecated interface

go.mod, go.sum
Change-Id: If5da928dcac01b541ac9a06d2e689ec3b9cde1b3
en:
zh(optional):
=> chore: update ollama to v0.4.0 to fix security alerts

go.mod, go.sum
=> feat: upgrade devops version to v0.1.6

flow/agent/manus/go.mod, flow/agent/manus/go.sum
=> feat: upgrade manus openai

quickstart/eino_assistant/eino/knowledgeindexing/orchestration.go
Change-Id: Ibc3dd1bcb817be9bbf6a27b29b56578722b24473
refactor: Adjust edge addition order in pipeline graph construction
This PR refactors the order in which edges are added to the pipeline graph. The sequence of `AddEdge` calls was modified to ensure the correct flow between nodes. No logic is changed, but the order is now more logical and maintainable.
=> refactor: Adjust edge addition order in pipeline graph construction

quickstart/eino_assistant/pkg/tool/open/open.go
fix
en:
When I try to implement the [eino assistant example](https://github.com/cloudwego/eino-examples/tree/main/quickstart/eino_assistant), I found there are a few issue on the "open tool" implementation, which can casue to a buggy output.
I found the original [`isfilePath` function](https://github.com/cloudwego/eino-examples/blob/cf6cb2dccc65463b08d4f064207e3e50bd6421a0/quickstart/eino_assistant/pkg/tool/open/open.go#L93C1-L95C2) has a very simple logic problem, and I try to fix this in my pr. 
And I also add logic to support the cross-platform compatibility. And I've already tested all the changes.
zh(optional):
=> fix: fix the issue of the open tool in the eino agent example and add some features

devops/debug/graph/graph.go, devops/debug/main.go
=> feat(devops): add an example of map[string]any

adk/layered_supervisor/agent.go, adk/supervisor/agent.go
=> feat: adk examples use common model

compose/workflow/1_simple/main.go, compose/workflow/2_field_mapping/main.go, compose/workflow/3_data_only/main.go, compose/workflow/4_control_only_branch/main.go, compose/workflow/5_static_values/main.go, compose/workflow/6_stream_field_map/main.go
add examples for eino's workflow API
=> feat: workflow examples
